### PR TITLE
Dev l00179085 jolly DGW117-  Integrated OWASP  in CICD pipeline

### PR DESCRIPTION
**Pull request by jollyjerinjoy**
Owasp yml added Dev l00179085 jolly dDGW117

### CODE REVIEW

**Comment by shreyashettys202** [comment]
can you please attach report generated by OWASP

**Comment by shreyashettys202** [comment]
Always make sure keep base branch to develop not main.as of now i have changed. Give proper message to PR message

**Comment by jollyjerinjoy** [comment]
Hi ,please review and approve PR -Dev L00179085 jolly DGW117  - 
DGW-117 Integrated OWASP  in CICD pipeline.
Output can be found here
[OWASP.Result.docx](https://github.com/shreyashettys202/DevOps2023-2024-Group3/files/14285387/OWASP.Result.docx)

**Comment by L00179085** [comment]
Hi ,please review and approve PR -Dev L00179085 jolly DGW117 -

DGW-117 Integrated OWASP in CICD pipeline.
Latest Output can be found here:
[OWASP.Result.docx](https://github.com/shreyashettys202/DevOps2023-2024-Group3/files/14285666/OWASP.Result.docx)

**Comment by pavankalyanvarikolu** [comment]
@jollyjerinjoy please add sample to similar to the below attached ss
Screenshot 2024-02-15 052339

**Comment by L00179085** [comment]
I have updated one sample url .. for OWASP ZAP scan BASELINE report. https://github.com/jollyjerinjoy/myreactapp/issues/5  as per https://www.zaproxy.org/blog/2020-04-09-automate-security-testing-with-zap-and-github-actions/  
Attaching report
[zap_scan.zip](https://github.com/shreyashettys202/DevOps2023-2024-Group3/files/14293237/zap_scan.zip)
[zap-report.zip](https://github.com/shreyashettys202/DevOps2023-2024-Group3/files/14293238/zap-report.zip)

target url - to be changed with respect to our project url which we set to access.

**Comment by jollyjerinjoy** [comment]
Hi ,Please review and approve PR -Dev L00179085 jolly DGW117 

Updated OWASP-ZAP.yml with following changes for reports.

     - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
         
          path: |
            report_html.html
            report_json.json

**Comment by pavankalyanvarikolu** [comment]
it is working fine for testing. when we click on the link it is downloading zip file from that we can able to see the dashboard in browser. @shreyashettys202 @Abhi9705  please review it from your side.

**Review by shreyashettys202 — APPROVED** [review]

**Pull request merged**
